-- COMANDOS PARA CRIAR BANCO DE DADOS

CREATE DATABASE ACADEMIA_LEONARDO;

CREATE DATABASE ACADEMIA_LEONARDO2;

-- COMANDOS PARA APAGAR BANCO DE DADOS

DROP DATABASE ACADEMIA_LEONARDO2;

-- COMANDO PARA ATIVAR BANCO DE DADOS

USE ACADEMIA_LEONARDO;

-- COMANDO MOSTRAR TABELA BANCO DE DADOS

SHOW TABLES;

-- COMANDOS PARA CRIAR TABELAS

CREATE TABLE Clientes (
ID_Cliente INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(32) NOT NULL,
Localizacao VARCHAR(58),
Telefone VARCHAR(20),
CPF VARCHAR(11) NOT NULL,
Data_Nascimento DATETIME NOT NULL
);

CREATE TABLE Pedidos (
ID_Pedidos INT AUTO_INCREMENT PRIMARY KEY,
Numero_Pedido INT NOT NULL,
Quantidade INT,
Nome_Cliente VARCHAR(32) NOT NULL,
Tempo_Espera DATE,
Marca VARCHAR(9)
);

CREATE TABLE Delivery (
ID_Delivery INT AUTO_INCREMENT PRIMARY KEY,
Localizacao VARCHAR(58),
Nota_Fiscal VARCHAR(58),
Informacoes_Produto VARCHAR(58) NOT NULL,
Metodo_Pagamento INT,
Informacoes_Cliente VARCHAR(58) NOT NULL
);

-- COMANDO PARA ALTERAR INFORMAÇÕES
-- ADICIONAR UM NOVO ATRIBUTO

ALTER TABLE Clientes  ADD Telefone VARCHAR(15);

-- ALTERAR O TIPO DE DADOS E TAMANHO

ALTER TABLE Clientes MODIFY Telefone VARCHAR(15);

-- RENOMEAR O NOME DO ATRIBUTO
-- ALTER TABLE ALUNOS CHANGE TELEFONE CELULAR (15);

-- EXCLUIR ATRIBUTO
ALTER TABLE Clientes DROP COLUMN Telefone;

-- LIMPAR DADOS DA TABELA
TRUNCATE TABLE Clientes;