CREATE DATABASE CASTELLO_EXTENSAO 
    DEFAULT CHARACTER SET = 'utf8mb4';

USE CASTELLO_EXTENSAO;

-- VISUALIZAR TABELAS DO BANCO DE DADOS
SHOW TABLE;

-- VISUALIZAR TODOS BANCO DE DADOS
SHOW SCHEMAS CASTELLO_EXTENSAO;

-- CRIAR TABELAS
CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_CLIENTE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CPF CHAR(14) NOT NULL UNIQUE,
    TELEFONE CHAR(15),
    DATA_NASCIMENTO DATETIME,
    STATUS ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- APAGAR BANCO DE DADOS
DROP DATABASE CASTELLO_EXTENSAO;

-- DESCRIÇÃO DA TABELA ALUNOS
-- INFORMAR OS ATRIBUTOS E TIPOS DE DADOS
DESCRIBE ALUNOS;